{
    "Animated": true,
    "CompletionTimeout": 3,
    "Message": "Checking for Updates...",
    "OnSuccess": "/LigaBasketballNba/Actions/AppUpdate.action",
    "_Type": "Action.Type.ProgressBanner"
}